In [3]:
import numpy as np
import random

from utils.gradcheck import gradcheck_naive, grad_tests_softmax, grad_tests_negsamp
from utils.utils import normalizeRows, softmax


In [4]:
a = np.array([1,2,3])
a.T

array([1, 2, 3])

In [7]:
np.sum(a)

6

In [16]:
b = np.array([[2,3,4],[5,6,7],[8,7,8]])
b[[0,2]] = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 6]])

In [14]:
b[:1]

array([[2, 3, 4]])

In [19]:
a = {"hi":3, "ho":4, "he":5}


KeyError: ('hi', 'he')